### ISSUE TITLE
Missing SimpleTask.h

### ISSUE THREAD

**Issue by henricazottes** [DennisB66/Simple-WebServer-Library-for-Arduino#1]
Hi,

Nice library at first look, but when trying to compile I get a missing library error:
```
src/SimpleWebServer.h:21:24: fatal error: SimpleTask.h: No such file or directory
```

I did install the Simple Utility dependency but there is no such file as SimpleTask.h...

Any help for that ?

**Comment by Domochip** [comment]
Hi,

It seems SimpleTask has been removed from simple-utility since version 0.3.
Could you reintegrate it into this simple-webserver?

thanks

**Comment by DennisB66** [comment]
SimpleTask is now part of a separate library (https://github.com/DennisB66/Simple-Scheduler-Library-for-Arduino) as I has use for the code independent of the webserver code.

Sorry for the late response and messing this up a little. I might consider moving to monorepo to cover all instead somewhere in the future.

//Dennis
